# Generated by Django 5.1.4 on 2024-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("transcription", models.TextField(blank=True)),
                ("ingredients", models.TextField(blank=True)),
                ("recipe_json", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
    ]
